---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: myweb-app
  namespace: default
  labels:
    app: myweb-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myweb-app
  template:
    metadata:
      labels:
        app: myweb-app
    spec:
      containers:
      - name: mywebapp-container
        image: "mai23005/mywebapp-image:v1.0"
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: myweb-app
  namespace: default
spec:
  selector:
    app: myweb-app
  type: NodePort
  ports:
  - name: http
    targetPort: 8080
    port: 80