---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: myweb-app
  namespace: default
  labels:
    app: myweb-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myweb-app
  template:
    metadata:
      labels:
        app: myweb-app
    spec:
      containers:
      - name: mywebapp-container
        image: "ghcr.io/andgeo69/myweb-app-repo:master"
        ports:
          - containerPort: 8080
        imagePullPolicy: Always
        resources:
          requests:
            cpu: ".1"
            memory: ".1Gi"
          limits:
            cpu: ".1"
            memory: ".1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-upstream
  labels:
    app: ingress-upstream
spec:
  selector:
    app: myweb-app
  ports:
    - name: 80-to-8080
      protocol: TCP
      port: 80
      targetPort: 8080
