---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: myweb-app
  namespace: default
  labels:
    app: myweb-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myweb-app
  template:
    metadata:
      labels:
        app: myweb-app
    spec:
      containers:
      - name: mywebapp-container
        image: "mai23005/mywebapp-image:latest"
        ports:
          - containerPort: 8080
        imagePullPolicy: Always
        resources:
          requests:
            cpu: ".1"
            memory: ".1Gi"
          limits:
            cpu: ".1"
            memory: ".1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: myweb-app-service
  labels:
    app: myweb-app-service
  namespace: default
spec:
  selector:
    app: myweb-app
  type: ClusterIP
  ports:
  - name: http
    targetPort: 8080
    port: 80
